###############################################################################
# Simple API Key Authentication Baseline for Performance Testing
# This provides a lightweight auth alternative to TokenReview + SubjectAccessReview
###############################################################################

# API Key Secrets for performance testing
---
apiVersion: v1
kind: Secret
metadata:
  name: perftest-user1-apikey
  namespace: openshift-ingress
  labels:
    kuadrant.io/auth-secret: "true"
    app: maas-simple-auth
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: perftest-user1
stringData:
  api_key: perftest-user1-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: perftest-user2-apikey
  namespace: openshift-ingress
  labels:
    kuadrant.io/auth-secret: "true"
    app: maas-simple-auth
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: perftest-user2
stringData:
  api_key: perftest-user2-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: perftest-user3-apikey
  namespace: openshift-ingress
  labels:
    kuadrant.io/auth-secret: "true"
    app: maas-simple-auth
  annotations:
    kuadrant.io/groups: free
    secret.kuadrant.io/user-id: perftest-user3
stringData:
  api_key: perftest-user3-key
type: Opaque

# HTTPRoute for simple auth path
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simple-auth-model-route
  namespace: llm
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
    namespace: openshift-ingress
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /simple/llm/facebook-opt-125m-simulated/v1/chat/completions
    backendRefs:
    - group: ""
      kind: Service
      name: facebook-opt-125m-simulated-kserve-workload-svc
      port: 8000
      weight: 1
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /v1/chat/completions

# Simple AuthPolicy for the simple path only
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: simple-auth-policy
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: simple-auth-model-route

  rules:
    authentication:
      api-key-users:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: maas-simple-auth
        credentials:
          authorizationHeader:
            prefix: APIKEY

    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
                groups:
                  selector: auth.identity.metadata.annotations.kuadrant\.io/groups